name: AdminPlus
description: AdminPlus allows you to ban, kick, op and other tasks on your server
main: com.connorlinfoot.adminplus.Main
version: 1.0.2
commands:
  admin:
    description: Open the admin menu from Admin Plus
permissons:
  adminplus.use:
    default: op
  adminplus.changetime:
    default: op
  adminplus.changedifficulty:
    default: op
  adminplus.kickplayers:
    default: op
  adminplus.banplayers:
    default: op
  adminplus.opplayers:
    default: op